const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const prisma = require('../lib/prisma');
const { authMiddleware } = require('../middleware/auth');

const router = express.Router();

// File storage setup
const uploadDir = path.join(__dirname, '../../uploads');
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

const storage = multer.diskStorage({
    destination: uploadDir,
    filename: (req, file, cb) => {
        const unique = Date.now() + '-' + Math.round(Math.random() * 1e9);
        cb(null, unique + path.extname(file.originalname));
    },
});

const upload = multer({
    storage,
    limits: { fileSize: 20 * 1024 * 1024 }, // 20MB
    fileFilter: (req, file, cb) => {
        const allowed = ['.pdf', '.jpg', '.jpeg', '.png', '.webp'];
        const ext = path.extname(file.originalname).toLowerCase();
        if (allowed.includes(ext)) cb(null, true);
        else cb(new Error('File type not allowed'));
    },
});

// AI Summary generation (mock or OpenAI)
async function generateSummary(text) {
    if (process.env.OPENAI_API_KEY) {
        try {
            const { default: OpenAI } = await import('openai');
            const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
            const resp = await client.chat.completions.create({
                model: 'gpt-4o-mini',
                messages: [
                    { role: 'system', content: 'You are a medical report analyzer. Provide a brief, clear summary of the key findings from this medical report in 2-3 sentences. Use plain language.' },
                    { role: 'user', content: text.slice(0, 4000) }
                ],
                max_tokens: 200,
            });
            return resp.choices[0].message.content;
        } catch (e) {
            console.error('OpenAI error:', e.message);
        }
    }
    // Mock summary
    return `Report uploaded successfully. Key metrics appear within normal range. Please consult your physician for a detailed interpretation of the results.`;
}

// POST /reports/upload
router.post('/upload', authMiddleware, upload.single('file'), async (req, res) => {
    try {
        const { reportName, reportType, reportDate, hospitalLab, doctorName, isCritical } = req.body;
        let fileUrl = null;
        let autoSummary = null;

        if (req.file) {
            fileUrl = `/uploads/${req.file.filename}`;
            // Try text extraction from PDF
            if (req.file.mimetype === 'application/pdf' || req.file.originalname.endsWith('.pdf')) {
                try {
                    const pdfParse = require('pdf-parse');
                    const buffer = fs.readFileSync(req.file.path);
                    const pdfData = await pdfParse(buffer);
                    autoSummary = await generateSummary(pdfData.text);
                } catch (e) {
                    autoSummary = await generateSummary('Medical report uploaded');
                }
            } else {
                autoSummary = await generateSummary('Medical image/report uploaded');
            }
        }

        const report = await prisma.medicalReport.create({
            data: {
                userId: req.user.id,
                reportName: reportName || req.file?.originalname || 'Unnamed Report',
                reportType: reportType || 'general',
                fileUrl,
                reportDate,
                hospitalLab,
                doctorName,
                autoGeneratedSummary: autoSummary,
                isCritical: isCritical === 'true' || isCritical === true,
            },
        });

        if (isCritical === 'true' || isCritical === true) {
            await prisma.healthAlert.create({
                data: {
                    userId: req.user.id,
                    alertType: 'report',
                    severity: 'critical',
                    title: `Critical Report: ${reportName}`,
                    message: `A critical medical report has been added to your vault. Please review immediately.`,
                },
            });
        }

        res.status(201).json(report);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// GET /reports
router.get('/', authMiddleware, async (req, res) => {
    try {
        const reports = await prisma.medicalReport.findMany({
            where: { userId: req.user.id },
            orderBy: { createdAt: 'desc' },
        });
        res.json(reports);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// DELETE /reports/:id
router.delete('/:id', authMiddleware, async (req, res) => {
    try {
        const report = await prisma.medicalReport.findFirst({ where: { id: req.params.id, userId: req.user.id } });
        if (report?.fileUrl) {
            const filePath = path.join(__dirname, '../../', report.fileUrl);
            if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
        }
        await prisma.medicalReport.deleteMany({ where: { id: req.params.id, userId: req.user.id } });
        res.json({ message: 'Deleted' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;
