'use client';
import AppLayout from '@/components/AppLayout';
import { useLang } from '@/lib/language-context';
import { useEffect, useState } from 'react';
import { getReports, uploadReport, deleteReport } from '@/lib/api';
import { FolderHeart, Upload, Trash2, FileText, AlertTriangle, X, Download } from 'lucide-react';

export default function VaultPage() {
    const { t } = useLang();
    const [reports, setReports] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [showUpload, setShowUpload] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const [form, setForm] = useState({ reportName: '', reportType: 'general', reportDate: '', hospitalLab: '', doctorName: '', isCritical: false });

    const load = () => {
        setLoading(true);
        getReports().then(res => setReports(res.data || [])).catch(() => { }).finally(() => setLoading(false));
    };
    useEffect(load, []);

    const handleUpload = async () => {
        if (!file) return;
        const fd = new FormData();
        fd.append('file', file);
        Object.entries(form).forEach(([k, v]) => fd.append(k, String(v)));
        await uploadReport(fd);
        setShowUpload(false);
        setFile(null);
        setForm({ reportName: '', reportType: 'general', reportDate: '', hospitalLab: '', doctorName: '', isCritical: false });
        load();
    };

    const handleDelete = async (id: string) => {
        await deleteReport(id);
        setReports(reports.filter(r => r.id !== id));
    };

    const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';

    return (
        <AppLayout>
            <div className="animate-in">
                <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <div>
                        <h1><span className="gradient-text-blue">{t('medical_records')}</span></h1>
                        <p>Upload, manage, and view your medical reports with AI summaries</p>
                    </div>
                    <button className="btn-blue" onClick={() => setShowUpload(true)}><Upload size={16} /> {t('upload_report')}</button>
                </div>

                {loading ? <div style={{ display: 'flex', justifyContent: 'center', padding: 40 }}><div className="spinner" /></div> : reports.length === 0 ? (
                    <div className="empty-state"><FolderHeart size={48} /><p>{t('no_records')}</p></div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                        {reports.map((r: any) => (
                            <div key={r.id} className="record-card">
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                    <div style={{ flex: 1 }}>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                                            <FileText size={16} color="var(--blue-light)" />
                                            <strong>{r.reportName}</strong>
                                            <span className="badge badge-blue">{r.reportType}</span>
                                            {r.isCritical && <span className="badge badge-rose"><AlertTriangle size={12} /> {t('critical')}</span>}
                                        </div>
                                        <div style={{ fontSize: 13, color: 'var(--text-secondary)', display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                                            {r.reportDate && <span>{t('report_date')}: {r.reportDate}</span>}
                                            {r.hospitalLab && <span>{t('hospital')}: {r.hospitalLab}</span>}
                                            {r.doctorName && <span>{t('doctor_name')}: {r.doctorName}</span>}
                                        </div>
                                        {r.autoGeneratedSummary && (
                                            <div style={{ marginTop: 8, padding: 10, borderRadius: 10, background: 'rgba(59,130,246,0.06)', border: '1px solid rgba(59,130,246,0.15)', fontSize: 13 }}>
                                                <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--blue-light)' }}>{t('ai_summary')}</span><br />
                                                {r.autoGeneratedSummary}
                                            </div>
                                        )}
                                    </div>
                                    <div style={{ display: 'flex', gap: 6 }}>
                                        {r.fileUrl && <a href={`${apiUrl}${r.fileUrl}`} target="_blank" className="btn-secondary" style={{ padding: '6px 10px' }}><Download size={14} /></a>}
                                        <button className="btn-danger" onClick={() => handleDelete(r.id)}><Trash2 size={14} /></button>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {showUpload && (
                    <div className="modal-overlay" onClick={() => setShowUpload(false)}>
                        <div className="modal-box" onClick={e => e.stopPropagation()}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
                                <h2 style={{ fontSize: 18, fontWeight: 700 }}>{t('upload_report')}</h2>
                                <button onClick={() => setShowUpload(false)} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}><X size={20} /></button>
                            </div>
                            <div className="form-group"><label className="form-label">{t('report_name')}</label><input className="input-field" value={form.reportName} onChange={e => setForm({ ...form, reportName: e.target.value })} /></div>
                            <div className="form-row">
                                <div className="form-group"><label className="form-label">{t('report_type')}</label><select className="input-field" value={form.reportType} onChange={e => setForm({ ...form, reportType: e.target.value })}><option value="general">General</option><option value="blood">Blood Test</option><option value="xray">X-Ray</option><option value="mri">MRI</option><option value="ct">CT Scan</option><option value="prescription">Prescription</option></select></div>
                                <div className="form-group"><label className="form-label">{t('report_date')}</label><input className="input-field" type="date" value={form.reportDate} onChange={e => setForm({ ...form, reportDate: e.target.value })} /></div>
                            </div>
                            <div className="form-row">
                                <div className="form-group"><label className="form-label">{t('hospital')}</label><input className="input-field" value={form.hospitalLab} onChange={e => setForm({ ...form, hospitalLab: e.target.value })} /></div>
                                <div className="form-group"><label className="form-label">{t('doctor_name')}</label><input className="input-field" value={form.doctorName} onChange={e => setForm({ ...form, doctorName: e.target.value })} /></div>
                            </div>
                            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                                <input type="checkbox" checked={form.isCritical} onChange={e => setForm({ ...form, isCritical: e.target.checked })} id="critical" />
                                <label htmlFor="critical" style={{ fontSize: 13, color: '#f43f5e', fontWeight: 600 }}>{t('critical')}</label>
                            </div>
                            <div className="drop-zone" onClick={() => document.getElementById('file-upload')?.click()} style={{ marginBottom: 16 }}>
                                <input id="file-upload" type="file" hidden accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e => setFile(e.target.files?.[0] || null)} />
                                {file ? <p style={{ color: 'var(--green-light)', fontWeight: 600 }}>{file.name}</p> : <p style={{ color: 'var(--text-muted)' }}>Click to select PDF or image file</p>}
                            </div>
                            <button className="btn-blue" onClick={handleUpload} disabled={!file} style={{ width: '100%', justifyContent: 'center' }}><Upload size={16} /> {t('upload_report')}</button>
                        </div>
                    </div>
                )}
            </div>
        </AppLayout>
    );
}
